=== mahesh-msk/sam5/VueExplorateurPlugin/ressources/xml/missions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="document" type="typeDocument"></xsd:element>

	<xsd:complexType name="typeDocument">
		<xsd:sequence>
			<xsd:element name="ListeMission" type="typeListeMission"
				maxOccurs="1" minOccurs="1"></xsd:element>
			<xsd:element name="ListeRegoupementTemps" type="typeListeRegroupementTemps"
				maxOccurs="1" minOccurs="1"></xsd:element>
		</xsd:sequence>

	</xsd:complexType>
	<xsd:complexType name="typeListeMission">
		<xsd:sequence>
			<!-- il peut y avoir de 1 à n missions par fichier de parcours -->
			<xsd:element name="Mission" type="typeMission" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="typeMission">
		<xsd:sequence>
			<xsd:element name="DateDebut" type="xsd:dateTime"
				minOccurs="1" maxOccurs="1" />
			<xsd:element name="DateFin" type="xsd:dateTime"
				minOccurs="1" maxOccurs="1" />
			<xsd:element name="OffsetDebut" type="xsd:long"
				minOccurs="1" maxOccurs="1" />
			<xsd:element name="OffsetFin" type="xsd:long" minOccurs="1"
				maxOccurs="1" />
			<xsd:element name="IdMessageDebut" type="xsd:integer" />
			<xsd:element name="ListeSegment" type="typeListeSegment"
				minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
		<!-- Identifiant unique de la mission dans le fichier xml -->
		<xsd:attribute name="id" use="required" type="xsd:ID" />
		<!-- Numéro de la mission dans le fichier xml (permettra d'ordonner les 
			missions dans l'affichage) -->
		<xsd:attribute name="numero" use="required" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="typeListeSegment">
		<xsd:sequence>
			<!-- Une mission peut contenir de 0 (cas de JRU) à n (autres parseurs) 
				segments de temps -->
			<xsd:element name="Segment" type="typeSegment" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="typeSegment">
		<xsd:sequence>
			<xsd:element name="OffsetDebut" type="xsd:long" />
			<xsd:element name="OffsetFin" type="xsd:long" />
			<xsd:element name="IdMessageDebut" type="xsd:integer" />
			<xsd:element name="DateDebut" type="xsd:dateTime"
				minOccurs="1" maxOccurs="1" />
			<xsd:element name="DateFin" type="xsd:dateTime"
				minOccurs="1" maxOccurs="1" />
		</xsd:sequence>
		<!-- Numéro du segment dans le fichier xml (permettra d'ordonner les segments 
			dans l'affichage) -->
		<xsd:attribute name="numero" use="required" type="xsd:integer"/>
	</xsd:complexType>

	<xsd:complexType name="typeListeRegroupementTemps">
		<xsd:sequence>
			<!-- il peut y avoir de 1 à n regroupements de temps -->
			<xsd:element name="RegroupementTemps" type="typeRegroupementTemps"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="typeRegroupementTemps">

		<xsd:sequence>
			<!-- Valeur du mois de regoupement exemple: 10/2010 -->
			<xsd:element name="Mois" type="xsd:dateTime"></xsd:element>
			<xsd:element name="ListeMission" type="typeListeRefMission"></xsd:element>
		</xsd:sequence>

		<!-- Identifiant unique du regroupement dans le fichier xml -->
		<xsd:attribute name="id" use="required" type="xsd:ID" />
		<!-- Numéro du regroupement dans le fichier xml (permettra d'ordonner les 
			regroupements dans l'affichage) -->
		<xsd:attribute name="numero" use="required" type="xsd:integer"/>

	</xsd:complexType>

	<xsd:complexType name="typeListeRefMission">
		<xsd:sequence>
			<xsd:element name="Mission" minOccurs="1"
				maxOccurs="unbounded" type="typeRefMission"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="typeRefMission">
		<xsd:attribute name="reference" type="xsd:IDREF" use="required"></xsd:attribute>
	</xsd:complexType>

</xsd:schema>

=== mahesh-msk/sam5/VueExplorateurPlugin/ressources/xml/missionsJRU.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="missions.xsd">
	<ListeMission>
		<Mission id="mission1" numero="1">
			<DateDebut>2001-12-01T12:00:00</DateDebut>
			<DateFin>2001-12-04T12:00:00</DateFin>
			<OffsetDebut>0</OffsetDebut>
			<OffsetFin>500</OffsetFin>
			<IdMessageDebut>1</IdMessageDebut>
		</Mission>
		<Mission id="mission2" numero="2">
			<DateDebut>2001-12-04T12:00:00</DateDebut>
			<DateFin>2001-12-31T12:00:00</DateFin>
			<OffsetDebut>501</OffsetDebut>
			<OffsetFin>1000</OffsetFin>
			<IdMessageDebut>101</IdMessageDebut>
		</Mission>
	</ListeMission>
	<ListeRegoupementTemps>
		<RegroupementTemps id="idvalue1" numero="1">
			<Mois>2001-12-01T00:00:00</Mois>
			<ListeMission>
				<Mission reference="mission1" />
				<Mission reference="mission2" />
			</ListeMission>
		</RegroupementTemps>
	</ListeRegoupementTemps>
</document>
