=== mahesh-msk/sam5/SAMNG_Framework/src/com/faiveley/samng/principal/sm/parseconfigatess/ConfigurationATESS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by PHILIPPE CHRISTIAN (FAIVELEY TRANSPORT TOURS SAS) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" elementFormDefault="qualified">
	<xs:element name="configuration-atess">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fichier-description"/>
				<xs:element ref="liste-identifiants-etendus"/>
				<xs:element ref="liste-maximum-compteur"/>
				<xs:element ref="table-evenements-variables"/>
				<xs:element ref="signature"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fichier-description">
		<xs:complexType>
			<xs:attributeGroup ref="attlist.fichier-description"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attlist.fichier-description">
		<xs:attribute name="xml-associe" type="xs:string" use="required"/>
	</xs:attributeGroup>
	<xs:element name="liste-identifiants-etendus">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="identifiant" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="liste-maximum-compteur">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="compteur-temps"/>
				<xs:element ref="compteur-distance"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="table-evenements-variables">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="evenement-variables" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="signature">
		<xs:complexType>
			<xs:attributeGroup ref="attlist.signature"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attlist.signature">
		<xs:attribute name="CRC" type="xs:string" use="required"/>
	</xs:attributeGroup>
	<xs:element name="identifiant">
		<xs:complexType>
			<xs:attributeGroup ref="attlist.identifiant"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attlist.identifiant">
		<xs:attribute name="code" type="xs:string" use="required"/>
		<xs:attribute name="nb_octets" type="xs:int" use="required"/>
	</xs:attributeGroup>
	<xs:element name="compteur-temps">
		<xs:complexType>
			<xs:attributeGroup ref="attlist.compteur-temps"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attlist.compteur-temps">
		<xs:attribute name="max" type="xs:int" use="required"/>
	</xs:attributeGroup>
	<xs:element name="compteur-distance">
		<xs:complexType>
			<xs:attributeGroup ref="attlist.compteur-distance"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attlist.compteur-distance">
		<xs:attribute name="max" type="xs:int" use="required"/>
	</xs:attributeGroup>
	<xs:element name="evenement-variables">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="liste-variables-atess" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="entree-logique" minOccurs="0"/>
			</xs:sequence>
			<xs:attributeGroup ref="attlist.evenement-variables"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attlist.evenement-variables">
		<xs:attribute name="code-evt" type="xs:int" use="required"/>
		<xs:attribute name="longueur" type="xs:int" use="required"/>
	</xs:attributeGroup>
	<xs:element name="liste-variables-atess">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="variable-atess" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="entree-logique">
		<xs:complexType>
			<xs:attributeGroup ref="attlist.entree-logique"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attlist.entree-logique">
		<xs:attribute name="code-entree-logique" type="xs:int" use="required"/>
		<xs:attribute name="valeur-entree-logique" default="false">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="true"/>
					<xs:enumeration value="false"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:element name="variable-atess">
		<xs:complexType>
			<xs:attributeGroup ref="attlist.variable-atess"/>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="attlist.variable-atess">
		<xs:attribute name="code-var" type="xs:int" use="required"/>
	</xs:attributeGroup>
</xs:schema>

=== mahesh-msk/sam5/com.wabtec.sam5.feature/userconfig/ressources/xml/ConfigurationNAV_DIESEL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by PHILIPPE CHRISTIAN (FAIVELEY TRANSPORT TOURS SAS) -->
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by FAIVELEY TRANSPORT (FAIVELEY TRANSPORT) -->
<configuration-atess xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationATESS.xsd">
	<fichier-description xml-associe="NAV_DIESEL.xml"/>
	<liste-identifiants-etendus>
		<identifiant code="3F"/>
		<identifiant code="7A"/>
	</liste-identifiants-etendus>
	<liste-maximum-compteur>
		<compteur-temps max="150"/>
		<compteur-distance max="1280"/>
	</liste-maximum-compteur>
	<table-evenements-variables>
		<evenement-variables code-evt="2" longueur="7">
			<!--IntroK7 : H, t-->
			<liste-variables-atess>
				<variable-atess code-var="3">
					<!--H-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="3" longueur="11">
			<!--EnteteFichier : H, t, E, i-->
			<liste-variables-atess>
				<variable-atess code-var="3">
					<!--H-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="6">
					<!--E-->
				</variable-atess>
				<variable-atess code-var="5">
					<!--i-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="4" longueur="7">
			<!--Mise en service cabine: H, t-->
			<liste-variables-atess>
				<variable-atess code-var="3">
					<!--H-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="5" longueur="3">
			<!--Mise hors service cabine: t-->
			<liste-variables-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="6" longueur="7">
			<!--Première mise en mouvement : H, t-->
			<liste-variables-atess>
				<variable-atess code-var="3">
					<!--H-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="7" longueur="3">
			<!--Mise en mouvement : t-->
			<liste-variables-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="8" longueur="4">
			<!--Arrêt : d, t-->
			<liste-variables-atess>
				<variable-atess code-var="1">
					<!--d-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="9" longueur="5">
			<!--RazCptHeure : H-->
			<liste-variables-atess>
				<variable-atess code-var="3">
					<!--H-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="10" longueur="3">
			<!--RazCptDistance: V-->
			<liste-variables-atess>
				<variable-atess code-var="2">
					<!--V-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="11" longueur="4">
			<!--SeuilVitesse : d, V-->
			<liste-variables-atess>
				<variable-atess code-var="1">
					<!--d-->
				</variable-atess>
				<variable-atess code-var="2">
					<!--V-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="12" longueur="13">
			<!--Introduction N° agent : H, t, A-->
			<liste-variables-atess>
				<variable-atess code-var="3">
					<!--H-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="7">
					<!--A-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="13" longueur="7">
			<!--Enregistrement LP :H, t-->
			<liste-variables-atess>
				<variable-atess code-var="3">
					<!--H-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="14" longueur="13">
			<!--Introduction N° train : H, t, N-->
			<liste-variables-atess>
				<variable-atess code-var="3">
					<!--H-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="10">
					<!--N-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="15" longueur="7">
			<!--Heure avant modif :H, t-->
			<liste-variables-atess>
				<variable-atess code-var="3">
					<!--H-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="16" longueur="7">
			<!--Heure après modif :H, t-->
			<liste-variables-atess>
				<variable-atess code-var="3">
					<!--H-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="32" longueur="7">
			<!--Message TBL1: d, t, V, Mess-->
			<liste-variables-atess>
				<variable-atess code-var="1">
					<!--d-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="2">
					<!--V-->
				</variable-atess>
				<variable-atess code-var="31">
					<!--Mess-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="33" longueur="12">
			<!--Taux vitesse TBL: d, t, V, TV, Vbut, Dbutt-->
			<liste-variables-atess>
				<variable-atess code-var="1">
					<!--d-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="2">
					<!--V-->
				</variable-atess>
				<variable-atess code-var="25">
					<!--TV-->
				</variable-atess>
				<variable-atess code-var="35">
					<!--Vbut-->
				</variable-atess>
				<variable-atess code-var="37">
					<!--Dbutt-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="34" longueur="7">
			<!--Commande de FU TBL: t, d, V, FU-->
			<liste-variables-atess>
				<variable-atess code-var="1">
					<!--d-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="2">
					<!--V-->
				</variable-atess>
				<variable-atess code-var="41">
					<!--FU-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="35" longueur="6">
			<!--Carré TBL : d, t, V-->
			<liste-variables-atess>
				<variable-atess code-var="1">
					<!--d-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="2">
					<!--V-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="36" longueur="7">
			<!--Chaîne Pilote : d, t, V, CP, -->
			<liste-variables-atess>
				<variable-atess code-var="1">
					<!--d-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="2">
					<!--V-->
				</variable-atess>
				<variable-atess code-var="29">
					<!--CP-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="37" longueur="12">
			<!--Franchissement Balise : d, t, V, NB, Vbut, Dbutt-->
			<liste-variables-atess>
				<variable-atess code-var="1">
					<!--d-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="2">
					<!--V-->
				</variable-atess>
				<variable-atess code-var="39">
					<!--NB-->
				</variable-atess>
				<variable-atess code-var="35">
					<!--Vbut-->
				</variable-atess>
				<variable-atess code-var="37">
					<!--Dbutt-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="38" longueur="7">
			<!--Indic. sonores/état : d, t, V, S-->
			<liste-variables-atess>
				<variable-atess code-var="1">
					<!--d-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="2">
					<!--V-->
				</variable-atess>
				<variable-atess code-var="42">
					<!--S-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="39" longueur="10">
			<!--Vbut/Dbut : d, t, V, Vbuta, Vmaa, Dbuta-->
			<liste-variables-atess>
				<variable-atess code-var="1">
					<!--d-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="2">
					<!--V-->
				</variable-atess>
				<variable-atess code-var="36">
					<!--Vbuta-->
				</variable-atess>
				<variable-atess code-var="33">
					<!--Vmaa-->
				</variable-atess>
				<variable-atess code-var="38">
					<!--Dbuta-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="40" longueur="6">
			<!--Test journalier : H, TJ-->
			<liste-variables-atess>
				<variable-atess code-var="1">
					<!--d-->
				</variable-atess>
				<variable-atess code-var="4">
					<!--t-->
				</variable-atess>
				<variable-atess code-var="2">
					<!--V-->
				</variable-atess>
				<variable-atess code-var="36">
					<!--Vbuta-->
				</variable-atess>
				<variable-atess code-var="33">
					<!--Vmaa-->
				</variable-atess>
				<variable-atess code-var="38">
					<!--Dbuta-->
				</variable-atess>
			</liste-variables-atess>
		</evenement-variables>
		<evenement-variables code-evt="42" longueur="7">
